<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$airports=Data::get('airports');
Layout::includeLayout('administradornav');
?>

<head>
    <title>ListarAeroportos</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('tables.css')?>">

</head>

<div class="wrapper">
    <table>
        <th><h1>Lista de Aeroportos</h1></th>
        <th><a href="<?=URL::toRoute('airport/create')?>"><button class="btn btn-info">Adicionar</button></a></th>
    </table>
    <table class="table table-dark table-striped table-hover">

        <thead>
            <tr>
                <th scope="col">ID do Aeroporto</th>
                <th scope="col">Nome do Aeroporto</th>
                <th scope="col">País</th>
                <th scope="col">Cidade</th>
                <th scope="col">Operações</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach ($airports as $airport){
            ?>
            <tr>
                <th scope="row"><?=$airport->airport_id?></th>
                <td><?=$airport->airport_name?></td>
                <td><?=$airport->country?></td>
                <td><?=$airport->city?></td>
                <td><a href="<?=URL::toRoute('airport/edit',$airport->airport_id)?>"><button class="btn btn-warning">Editar</button></a><a href="<?=URL::toRoute('airport/destroy',$airport->airport_id)?>"><button class="btn btn-danger">Eliminar</button></a></td>
        </tr>
        <?php
        }
        ?>

        </tbody>
    </table>
