<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$airports=Data::get('airports');
Layout::includeLayout('administradornav');
?>

<head>
    <title>ListarAeroportos</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('tables.css')?>">

</head>

<div class="wrapper">
    <table>
        <th><h1>Lista de Aeroportos</h1></th>
        <th><button class="btn btn-info">Adicionar</button></th>
    </table>
    <table class="table table-dark table-striped table-hover">

        <thead>
            <tr>
                <th scope="col">ID do Aeroporto</th>
                <th scope="col">Nome do Aeroporto</th>
                <th scope="col">País</th>
                <th scope="col">Cidade</th>
                <th scope="col">Operações</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Aeroporto Humberto Delgado</td>
                <td>Portugal</td>
                <td>Lisboa</td>
                <td><button class="btn btn-warning">Editar</button><button class="btn btn-danger">Eliminar</button></td>
            </tr>
        </tbody>
    </table>

</div>
