<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$ticket= Data::get('ticket');


    $html="<hr style='border: 5px'><h1 style='text-align: center'>Bilhete para o voo: " . $ticket->flight_id ."</h1><hr style='border: 5px'><br><h3 style='margin-left: 5%'>Origem:  ". $ticket->flight->origin_airport->airport_name . "  =>  Destino: ". $ticket->flight->destination_airport->airport_name . "</h3><hr style='border: 3px solid'>
        <h5><br>ID do Ticket:" . $ticket->ticket_id . "<hr style='border: 1px dotted'>Preço:".$ticket->total_price. "<br><hr style='border: 1px dotted'>Data de Compra da Passagem: " . $ticket->purchase_date . "<br><hr style='border: 1px dotted'> Ida e volta:" . $ticket->round_trip ."<br><hr style='border: 1px dotted'> Escalas:<h5><hr style='border: 1px dotted'>";

    foreach ($ticket->flight->scale as $scale){
        $html+= $scale->origin . "<br>" . $scale->destination;


    }


//chamar o dompdf com namespace por causa do conflito de nomes
use Dompdf\Dompdf;

// include autoloader
require_once 'D:\wamp64\www\PSI_PWS_REC\pdfs\autoload.inc.php';

//Criar a instancia
$pdf = new Dompdf();

//Colocar dados no PDF
$pdf->loadHtml('
'. $html . '
');

//renderizar o html
$pdf->render();

//mostrar a pagina
$pdf->stream(
    "Bilhete_voo_377",

    array(
        "Attachment" => false //true faz download automatico, false faz download facultativo
    )
);

?>