<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$tickets=Data::get('tickets');
Layout::includeLayout('operadorNav');

if(!isset($_SESSION['id'])){
    \ArmoredCore\WebObjects\Redirect::toRoute('user/login');
}

?>

<head>
    <title>ListarAeroportos</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('tables.css')?>">
    <link rel="stylesheet" href="<?=Asset::css('booststrap.min.css')?>"

</head>
<body>
<div class="wrapper">
    <table>
        <th><h1>Bilhetes sem checkin</h1></th>

    </table>
    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">ID do Bilhete</th>
                <th scope="col">Ida e volta</th>
                <th scope="col">Cliente</th>
                <th scope="col">Data de Compra</th>
                <th scope="col">Preço</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $i=0;
        foreach ($tickets as $ticket){
            ?>
            <tr>
                <th scope="row"><?=$ticket->ticket_id?></th>
                <td><?=$ticket->round_trip?></td>
                <td><?=$ticket->user->fullname?></td>
                <td><?=$ticket->purchase_date?></td>
                <td><?=$ticket->total_price?></td>
                <td><a href="<?=URL::toRoute('ticket/processCheckin',$ticket->ticket_id)?>"><button class="btn btn-warning">Fazer Checkin</button></a>
            </tr>

    <?php
    $i++;
    }
    ?>
        </tbody>
    </table>
</div>
</body>
