<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

if(isset($_SESSION['id'])){
    Layout::includeLayout('usernav');
}
else{
    Layout::includeLayout('nousernav');
}
?>

<head>
    <title>Procurar Voos</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('index.css')?>">

</head>
<body>
    <div class="center">
        <!---<div id="myCarousel" class="carousel slide" data-ride="carousel">
            Indicators
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

             Wrapper for slides
            <div class="carousel-inner">
                <div class="item active">
                    <img id="image1" src="<?=Asset::image('chicago.jpg')?>" alt="Chicago">
                </div>

                <div class="item">
                    <img id="image2" src="<?=Asset::image('newyork.jpg')?>" alt="New York">
                </div>

                <div class="item">
                    <img id="image3" src="<?=Asset::image('la.jpg')?>" alt="Los Angeles">
                </div>
            </div>

             Left and right controls
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>-->


    <!-- Intro -->
        <div class="center">
            <h1>Pesquisar Voo</h1>
            <form method="post" action="<?=URL::toRoute('flight/procurar')?>">
                <div class="select-box">
                    <label for="tipoPesquisa">Pesquisar por: </label>
                    <select id="tipoPesquisa" name="tipoPesquisa">
                        <option value="data"> Por data</option>
                        <option value="origemDestino">Por Origem e Destino</option>
                    </select>
                </div>
                    <input type="date" id="date_hour_departure" name="date_hour_departure" placeholder="Data de Partida">
                    <!--<div class="txt_field">-->
                        <input type="text" id="origin" name="origin" hidden required placeholder="Origem">
                        <span></span>
                <!--<label>Origem</label>
            </div>
            <div class="txt_field">-->
                        <input type="text" id="destination" name="destination" hidden required placeholder="Destino">
                        <span></span>

                <!-- <label>Destino</label>
             </div>-->
                    <input type="submit" value="Procurar">
        </div>
        </form>
    </div>

        <script>
            var content= document.getElementById("tipoPesquisa");
            content.onclick = function (event){
                if (content.value == "origemDestino"){
                    document.getElementById('date_hour_departure').style.display = 'none';
                    document.getElementById('origin').style.display = 'block';
                    document.getElementById('destination').style.display = 'block';

                }
                else {
                    document.getElementById('date_hour_departure').style.display = 'block';
                    document.getElementById('origin').style.display = 'none';
                    document.getElementById('destination').style.display = 'none';
                }

            }

        </script>
</body>

