<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$airplane=Data::get('airplane');

Layout::includeLayout('administradorNav'); ?>


<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('forms.css')?>">

</head>

<body>
<div class="center">
    <h1>Editar Informações do Aeroporto</h1>
    <form method="post" action="<?=URL::toRoute('airplane/update',$airplane->airplane_id)?>">
        <div class="txt_field">
            <input type="text" value="<?=$airplane->airplane_reference?>" name="airplane_reference" required>
            <span></span>
            <label>Referência do Avião</label>
        </div>
        <div class="txt_field">
            <input type="text" value="<?=$airplane->airplane_name?>" name="airplane_name" required>
            <span></span>
            <label>Nome do Aeroporto</label>
        </div>
        <div class="txt_field">
            <input type="text" value="<?=$airplane->capacity?>" name="capacity" required>
            <span></span>
            <label>Capacidade do Avião</label>
        </div>
        <div class="pass"></div>
        <input type="submit" value="Editar">

    </form>
</div>
</body>
