<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('gestorNav'); ?>

<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('forms.css')?>">

</head>

<body>
<div class="center">
    <h1>Registo de Avião</h1>
    <form method="post" action="<?=URL::toRoute('airplane/store')?>">
        <div class="txt_field">
            <input type="text" name="airplane_reference" required>
            <span></span>
            <label>Referência do Avião</label>
        </div>
        <div class="txt_field">
            <input type="text" name="airplane_name" required>
            <span></span>
            <label>Nome do Avião</label>
        </div>
        <div class="txt_field">
            <input type="text" name="capacity" required>
            <span></span>
            <label>Capacidade do Avião</label>
        </div>
        <div class="pass"></div>
        <input type="submit" value="Registar">
    </form>
</div>
</body>