<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$flights=Data::get('flights');
$origins=Data::get('origins');
$destinations=Data::get('destinations');
$airplanes=Data::get('airplanes');

if(!isset($_SESSION['id'])){
    \ArmoredCore\WebObjects\Redirect::toRoute('user/login');
}

if($_SESSION['profile']==3){
    Layout::includeLayout('gestornav');
}
else{
    Layout::includeLayout('usernav');
}


?>

<head>
    <title>ListarAeroportos</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('tables.css')?>">
    <link rel="stylesheet" href="<?=Asset::css('booststrap.min.css')?>"

</head>
<body>
<div class="wrapper">
    <table>
        <th><h1>Lista de Voos</h1></th>
        <?php
            if($_SESSION['profile']==3){?>
                <th><a href="<?=URL::toRoute('flight/create')?>"><button class="btn btn-info">Adicionar</button></a></th>
            <?php
            }
        ?>

    </table>
    <table class="table table-dark table-striped table-hover">

        <thead>
            <tr>
                <th scope="col">ID do Voo</th>
                <th scope="col">Preço do Voo</th>
                <th scope="col">Partida</th>
                <th scope="col">Chegada</th>
                <th scope="col">Distância</th>
                <th scope="col">Origem</th>
                <th scope="col">Destino</th>
                <th scope="col">Avião de partida</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $i=0;
        foreach ($flights as $flight){
            ?>
            <tr>
                <th scope="row"><?=$flight->flight_id?></th>
                <td><?=$flight->flight_price?></td>
                <td><?=$flight->date_hour_departure?></td>
                <td><?=$flight->date_hour_arrival?></td>
                <td><?=$flight->distance?></td>
                <td><?=$origins[$i]?></td>
                <td><?=$destinations[$i]?></td>
                <td><?=$flight->airplane->airplane_name?></td>
                <td><a href="<?= URL::toRoute('scale/showByFlightId',$flight->flight_id)?>"><button class="btn btn-info">Escalas</button></a></td>
                <?php
                    if($_SESSION['profile']==3){?>
                    <td><a href="<?=URL::toRoute('flight/edit',$flight->flight_id)?>"><button class="btn btn-warning">Editar</button></a><a href="<?=URL::toRoute('flight/destroy',$flight->flight_id)?>"><button class="btn btn-danger">Eliminar</button></a></td>
                <?php
                    }
                    else{?>
                        <td><a href="<?=URL::toRoute('ticket/confirmTicket',$flight->flight_id)?>"><button class="btn btn-success">Comprar</button>
                <?php
                    }
                ?>
            </tr>

    <?php
    }
    ?>
        </tbody>
    </table>
</div>



</body>
