<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$scales=Data::get('scales');
$origins=Data::get('origins');
$destinations=Data::get('destinations');
Layout::includeLayout('gestornav');

if(!isset($_SESSION['id'])){
    \ArmoredCore\WebObjects\Redirect::toRoute('user/login');
}

?>

<head>
    <title>ListarAeroportos</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('tables.css')?>">
    <link rel="stylesheet" href="<?=Asset::css('booststrap.min.css')?>"

</head>
<body>
<div class="wrapper">
    <table>
        <th><h1>Lista de Escalas do voo: <?=$_SESSION['flight_id']?></h1></th>
        <th><a href="<?=URL::toRoute('scale/create')?>"><button class="btn btn-info">Adicionar</button></a></th>
    </table>
    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">ID da Escala</th>
                <th scope="col">Distância</th>
                <th scope="col">Partida</th>
                <th scope="col">Chegada</th>
                <th scope="col">Avião</th>
                <th scope="col">Origem</th>
                <th scope="col">Destino</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $i=0;
        foreach ($scales as $scale){
            ?>
            <tr>
                <th scope="row"><?=$scale->scale_id?></th>
                <td><?=$scale->distance?></td>
                <td><?=$scale->date_hour_departure?></td>
                <td><?=$scale->date_hour_arrival?></td>
                <td><?=$scale->airplane->airplane_name?></td>
                <td><?=$origins[$i]?></td>
                <td><?=$destinations[$i]?></td>
                <td><a href="<?=URL::toRoute('scale/edit',$scale->scale_id)?>"><button class="btn btn-warning">Editar</button></a><a href="<?=URL::toRoute('scale/destroy',$scale->scale_id)?>"><button class="btn btn-danger">Eliminar</button></a></td>
            </tr>

    <?php
    $i++;
    }
    ?>
        </tbody>
    </table>
</div>
</body>
