<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('nousernav'); ?>

<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('forms.css')?>">

</head>

<body>
    <div class="center">
        <h1>Login</h1>
        <form method="post" action="<?=URL::toRoute('user/processLogin')?>">
            <div class="txt_field">
                <input type="text" name="username" required>
                <span></span>
                <label>Username</label>
            </div>
            <div class="txt_field">
                <input type="password" name="password" required>
                <span></span>
                <label>Password</label>
            </div>
            <div class="pass">Forgot Password?</div>
                <input type="submit" value="Login">
            </div>
        </form>
    </div>
</body>