<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('nousernav'); ?>

<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('forms.css')?>">

</head>

<body>
    <div class="center">
        <h1>Registo</h1>
        <form method="post" action="<?=URL::toRoute('user/store')?>">
                <div class="txt_field">
                    <input type="text" name="fullname" required>
                    <span></span>
                    <label>Nome Completo</label>
                </div>
                <!--<div class="txt_field">-->
                    <label id="dataNascimento">Data de Nascimento</label>
                    <input type="date" name="birth_date" required>
                    <span></span>

                <!--</div>-->
                <div class="txt_field">
                    <input type="text" name="email" required>
                    <span></span>
                    <label>Email</label>
                </div>
                <div class="txt_field">
                    <input type="text" name="phone_number" required>
                    <span></span>
                    <label>Número de Telemóvel</label>
                </div>
                <div class="txt_field">
                    <input type="text" name="username" required>
                    <span></span>
                    <label>Nome de Utilizador</label>
                </div>

                <div class="txt_field">
                    <input type="password" name="password" required>
                    <span></span>
                    <label>Palavra-Passe</label>
                </div>
                <div class="pass"></div>
                    <input type="submit" value="Registar">
                </div>
            </div
        </form>
    </div>
</body>