<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$users=Data::get('users');
$profiles=Data::get('profiles');


if(!isset($_SESSION['id'])){
    \ArmoredCore\WebObjects\Redirect::toRoute('user/login');
}

Layout::includeLayout('administradornav');
?>

<head>
    <title>Todos os Utilizadores</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?=Asset::css('tables.css')?>">

</head>

<div class="wrapper">
    <table>
        <th><h1>Lista de Utilizadores </h1></th>
    </table>
    <table class="table table-dark table-striped table-hover">

        <thead>
        <tr>
            <th scope="col">ID do Utilizador</th>
            <th scope="col">Nome do Utilizador</th>
            <th scope="col">Data de Nascimento</th>
            <th scope="col">Email</th>
            <th scope="col">Número de Telemóvel</th>
            <th scope="col">Pontos</th>
            <th scope="col">Perfil</th>

        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($users as $user){

            ?>
            <tr>
                <th scope="row"><?=$user->user_id?></th>
                <td><?=$user->fullname?></td>
                <td><?=$user->birth_date?></td>
                <td><?=$user->email?></td>
                <td><?=$user->phone_number?></td>
                <td><?=$user->points?></td>
                <?php
                if($_SESSION['profile']==1){
                ?>
                <td>
                    <form method="post" action="<?=URL::toRoute('user/changeProfile',$user->user_id)?>">
                        <select name="profile_id">
                            <option value="<?=$user->profile_id?>"><?=$user->ShowTypeOfUser($user->profile_id)?></option>
                            <?php
                            foreach ($profiles as $profile) {
                                if($user->profile_id!=$profile->profile_id){?>
                                    <option value="<?=$profile->profile_id?>"><?=$profile->profile_name?></option>
                                        <?php
                                }
                            }
                            ?>
                        </select>
                        </td><td>
                        <input class="btn btn-warning" type="submit" value="Alterar perfil do Utilizador">
                    </form>
                </td>
                <?php

                }
                ?>
            </tr>
            <?php
        }
        ?>

        </tbody>
    </table>

